version: '2.1'

services:

  coh-cor:
    build:
      context: .
    image: hmctspublic.azurecr.io/coh/cor:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cor-db:5432/cor
      - SPRING_DATASOURCE_USERNAME=cor
      - SPRING_DATASOURCE_PASSWORD=cor
      - IDAM_API_URL=http://idam-api:8080
      - S2S_URL=http://service-auth-provider-app:8489
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
    # these environment variables are used by java-logging library
      - ROOT_LOGGING_LEVEL=INFO
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=coh-cor
      - REFORM_TEAM=coh
      - REFORM_ENVIRONMENT=docker
    links:
     - cor-db
    depends_on:
     - cor-db
    ports:
    - $SERVER_PORT:8080
    - "7005:7005"