version: '2.1'

services:
  coh-cor:
    build:
      context: .
#    image: hmcts/coh-cor:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cor-db:5432/cor
      - SPRING_DATASOURCE_USERNAME=cor
      - SPRING_DATASOURCE_PASSWORD=cor
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
      - S2S_SECRET=AAAAAAAAAAAAAAAA
      - IDAM_SERVICE_NAME=coh-cor
      # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=coh-cor
      - REFORM_TEAM=coh
      - REFORM_ENVIRONMENT=docker
    links:
     - cor-db
    depends_on:
     - cor-db
    ports:
    - $SERVER_PORT:8080

  cor-db:
    image: postgres
    environment:
     - POSTGRES_USER=cor
     - POSTGRES_PASSWORD=cor
     - POSTGRES_DB=cor
#    ports:
#     - 5432:5432

