cor:
  postgresql:
    postgresqlUsername: coh
    postgresqlPassword: coh
    postgresqlDatabase: coh
    nameOverride: coh-cor-db
#  TODO Update the docker image
  image: 'hmcts.azurecr.io/hmcts/coh-cor:latest'
  aadIdentityName: coh
  applicationPort: 8080
  readinessDelay: 30
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 30
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  keyVaults:
    coh-cor:
      resourceGroup: coh-cor
      secrets:
        - AppInsightsInstrumentationKey
        - microservicekey-coh-cor
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/{{ .Values.postgresql.postgresqlDatabase}}?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    # Regardless of environment, point towards AAT instances. Overwrite in product charts if needed
    IDAM_API_BASE_URI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
#    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    #try adding S2S_URL
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    TEST_URL: https://coh-cor-{{ .Values.global.environment }}-staging.service.core-compute-{{ .Values.global.environment }}.internal
    ENABLE_DB_MIGRATE: true
    PACKAGES_ENVIRONMENT: local
    PACKAGES_PROJECT: coh
    PACKAGES_NAME: cor
    AUTHORIZATION_ROLES: solicitor,citizen,caseworker-sscs-judge,caseworker-sscs,caseworker-sscs-panelmember,jui-panelmember
    S2S_NAMES_WHITELIST: jui_webapp,sscs,divorce,ccd,em_gw
    LOG_LEVEL : "INFO"