cor:
  postgresql:
    postgresqlUsername: coh
    postgresqlPassword: coh
    postgresqlDatabase: coh
    nameOverride: coh-cor-db
#  TODO Update the docker image
  image: 'hmcts.azurecr.io/hmcts/coh-cor:latest'
  applicationPort: 8080
  readinessDelay: 30
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 30
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - AppInsightsInstrumentationKey
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-coh-cor
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgresql.nameOverride}}:5432/{{ .Values.postgresql.postgresqlDatabase}}?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    # Regardless of environment, point towards AAT instances. Overwrite in product charts if needed

    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    TEST_URL: https://coh-cor-aat-staging.service.core-compute-aat.internal

    ENABLE_DB_MIGRATE: true
    PACKAGES_ENVIRONMENT: local
    PACKAGES_PROJECT: coh
    PACKAGES_NAME: cor
    AUTHORIZATION_ROLES: solicitor,citizen,caseworker-sscs-judge,caseworker-sscs,caseworker-sscs-panelmember,jui-panelmember
    S2S_NAMES_WHITELIST: jui_webapp,sscs,divorce,ccd,em_gw