spring:
  application:
    name: Continuous Online Hearing
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: ${SHOW_SQL:true}
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coh}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:user}
    platform: postgresql
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.

  liquibase:
   enabled: false
   change-log: classpath:/db/changelog/db.changelog-master.yam

base-urls:
  idam-user: ${IDAM_API_URL:http://localhost:4501}
  idam-s2s: ${S2S_URL:http://localhost:4502}
  s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
  test-url: ${TEST_URL:http://localhost:8080}

event-scheduler:
  fixed-delay: 20000

#this need to be removed
info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:coh}
    name: ${PACKAGES_NAME:cor}

